### ISSUE TITLE
FluentValidation 9.x support

### ISSUE THREAD

**Issue by cplankl** [FluentValidation/FluentValidation-LegacyWeb#2]
Hello Jeremy,

I'm using the nuget package FluentValidation.Mvc5 in my project together with .Net 4.8. I want to upgrade to FluentValidation 9.x to use new features. I've seen that FluentValidation doesn't support Mvc5 anymore but I've also seen that on this repo you did some commits to support FluentValidation 9.0 but there isn't a NuGet package for this available. Do you plan to release a NuGet package for this legacy repository to support FluentValidation 9.0?

Kind regards
Chris

**Comment by JeremySkinner** [comment]
Hi Chris,

There are no plans to do an official release to support MVC5 with FluentValidation 9, although you are welcome to use the source code if you wish.
